-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as a, REST_REVIEW as b
WHERE a.ADDRESS LIKE "서울%"
AND a.REST_ID = b.REST_ID
GROUP BY a.REST_ID
ORDER BY AVG(b.REVIEW_SCORE) DESC, a.FAVORITES DESC